version: '3.8'

services:

  db:
    container_name: postgres_med
    image: postgres
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  redis:
    container_name: 'redis'
    image: 'redis:3.2.0'
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
      # - ./redis-data/:var/lib/redis/data

  app:
    container_name: app
    build: .
    # command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: always
    

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - 5050:80
    depends_on:
      - db

volumes:
  postgres_data:
  redis_data:



    # postgres:
  #   container_name: 'postgres'
  #   restart: always
  #   image: 'postgres:9.5.3'
  #   ports:
  #     - '5432:5432'
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./postgres-data/:var/lib/postgresql/data


    













